import { dice, type Dice } from './testing-random';

interface Field {
	name: string;
	type: string;
}

interface Built {
	name: string;
	keys: Field[][];
}

interface Kind {
	sql: string;
	defaults: string[];
	checks?: string[];
	plain?: boolean;
}

const WORDS = ['users', 'accounts', 'orders', 'items', 'invoices', 'payments', 'products', 'categories', 'tags', 'posts', 'comments', 'sessions', 'devices', 'events', 'tickets', 'teams', 'members', 'projects', 'tasks', 'files', 'notes', 'roles', 'permissions', 'regions', 'cities', 'shipments', 'warehouses', 'suppliers', 'reviews', 'coupons'];
const COLUMNS = ['name', 'title', 'email', 'status', 'kind', 'amount', 'price', 'qty', 'notes', 'created_at', 'updated_at', 'active', 'code', 'rank', 'score', 'balance', 'ratio', 'born_on', 'starts_at', 'ends_at', 'ip', 'tags', 'payload', 'label', 'level', 'weight', 'height', 'phone', 'website'];

const KINDS: Kind[] = [
	{ sql: 'integer', defaults: ['0', '1'], checks: ['{c} >= 0', '{c} BETWEEN 1 AND 1000', '{c} <> 13'], plain: true },
	{ sql: 'bigint', defaults: ['0'], checks: ['{c} > 0'], plain: true },
	{ sql: 'smallint', defaults: ['0', '7'], checks: ['{c} >= 0'], plain: true },
	{ sql: 'numeric(10,2)', defaults: ['0', '9.99'], checks: ['{c} >= 0', '{c} < 100000'], plain: true },
	{ sql: 'numeric(5,0)', defaults: ['0'], plain: true },
	{ sql: 'numeric(3,3)', defaults: ['0.5'], plain: true },
	{ sql: 'real', defaults: ['1.5'], plain: true },
	{ sql: 'double precision', defaults: ['0'], plain: true },
	{ sql: 'text', defaults: ["'x'", "''"], checks: ["char_length({c}) > 0", "{c} <> ''"], plain: true },
	{ sql: 'varchar(40)', defaults: ["'x'"], checks: ["{c} IN ('a', 'b', 'c')", 'char_length({c}) >= 2'], plain: true },
	{ sql: 'varchar(3)', defaults: ["'abc'"], plain: true },
	{ sql: 'char(2)', defaults: ["'ab'"], plain: true },
	{ sql: 'boolean', defaults: ['true', 'false'], plain: true },
	{ sql: 'date', defaults: ['CURRENT_DATE', "'2020-01-01'"], checks: ["{c} > '2000-01-01'"], plain: true },
	{ sql: 'time', defaults: ["'12:00'"], plain: true },
	{ sql: 'timestamp', defaults: ['now()', "'2020-01-01 00:00'"], plain: true },
	{ sql: 'timestamptz', defaults: ['now()', 'CURRENT_TIMESTAMP'], plain: true },
	{ sql: 'timestamp(3) with time zone', defaults: ['now()'], plain: true },
	{ sql: 'uuid', defaults: ['gen_random_uuid()'], plain: true },
	{ sql: 'jsonb', defaults: ["'{}'"] },
	{ sql: 'json', defaults: ["'{}'"] },
	{ sql: 'bytea', defaults: [] },
	{ sql: 'inet', defaults: ["'127.0.0.1'"] },
	{ sql: 'text[]', defaults: ["'{}'"] },
	{ sql: 'integer[]', defaults: [] },
	{ sql: 'money', defaults: [] },
	{ sql: 'interval', defaults: ["'1 day'"] },
	{ sql: 'bit(3)', defaults: ["B'101'"] },
	{ sql: 'tsvector', defaults: [] }
];

const ident = (name: string) => (/^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name.replaceAll('"', '""')}"`);

export function randomSql(seed: number): string {
	const d = dice(seed + 104729);
	const out: string[] = [];
	const enums: string[] = [];
	const domains: string[] = [];
	if (d.chance(0.35)) {
		const name = d.pick(['mood', 'level_kind', 'state_kind']);
		out.push(`CREATE TYPE ${name} AS ENUM ('low', 'mid', 'high')`);
		enums.push(name);
	}
	if (d.chance(0.2)) {
		out.push('CREATE DOMAIN positive AS integer CHECK (VALUE > 0)');
		domains.push('positive');
	}
	const built: Built[] = [];
	const used = new Set<string>();
	const pending: string[] = [];
	const total = d.int(2, 9);
	for (let i = 0; i < total; i++) {
		let base = d.pick(WORDS);
		while (used.has(base)) base = `${base}_${i}`;
		used.add(base);
		const name = d.chance(0.08) ? `${base[0]?.toUpperCase()}${base.slice(1)} Items` : base;
		const taken = new Set<string>();
		const lines: string[] = [];
		const keys: Field[][] = [];
		const claim = (wanted: string) => {
			let result = wanted;
			let n = 2;
			while (taken.has(result.toLowerCase())) result = `${wanted}_${n++}`;
			taken.add(result.toLowerCase());
			return result;
		};
		const style = d.pick(['serial', 'bigserial', 'identity', 'always', 'uuid', 'natural', 'composite', 'none', 'unique']);
		if (style === 'serial' || style === 'bigserial' || style === 'identity' || style === 'always' || style === 'uuid') {
			claim('id');
			const type = style === 'serial' ? 'integer' : style === 'uuid' ? 'uuid' : style === 'bigserial' || d.chance(0.5) ? 'bigint' : 'integer';
			const column = style === 'serial' ? 'id serial PRIMARY KEY' : style === 'bigserial' ? 'id bigserial PRIMARY KEY' : style === 'identity' ? `id ${type} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` : style === 'always' ? `id ${type} GENERATED ALWAYS AS IDENTITY PRIMARY KEY` : 'id uuid DEFAULT gen_random_uuid() PRIMARY KEY';
			lines.push(column);
			keys.push([{ name: 'id', type }]);
		} else if (style === 'natural') {
			claim('code');
			const type = d.pick(['varchar(8)', 'char(3)', 'varchar(20)']);
			lines.push(`code ${type} PRIMARY KEY`);
			keys.push([{ name: 'code', type }]);
		} else if (style === 'composite') {
			claim('part_a');
			claim('part_b');
			const a = d.pick(['integer', 'uuid', 'date']);
			const b = d.pick(['integer', 'varchar(10)', 'smallint']);
			lines.push(`part_a ${a} NOT NULL`, `part_b ${b} NOT NULL`, 'PRIMARY KEY (part_a, part_b)');
			keys.push([
				{ name: 'part_a', type: a },
				{ name: 'part_b', type: b }
			]);
		} else if (style === 'unique') {
			claim('ref_no');
			lines.push('ref_no integer NOT NULL UNIQUE');
			keys.push([{ name: 'ref_no', type: 'integer' }]);
		}
		if (d.chance(0.3)) {
			const column = claim(d.pick(['slug', 'handle']));
			lines.push(`${column} varchar(50) NOT NULL UNIQUE`);
			keys.push([{ name: column, type: 'varchar(50)' }]);
		}
		const plainFields: { name: string; kind: Kind | null; type: string }[] = [];
		for (let c = d.int(1, 5); c > 0; c--) {
			const column = claim(d.pick(COLUMNS));
			const special = d.chance(0.12) && enums.length > 0 ? d.pick(enums) : d.chance(0.08) && domains.length > 0 ? d.pick(domains) : null;
			const kind = special ? null : d.pick(KINDS);
			const type = special ?? (kind as Kind).sql;
			const parts = [column, type];
			const required = d.chance(0.55);
			if (required) parts.push('NOT NULL');
			const hasDefault = d.chance(0.3);
			if (hasDefault) {
				if (special && enums.includes(special)) parts.push("DEFAULT 'mid'");
				else if (special) parts.push('DEFAULT 1');
				else if (kind && kind.defaults.length > 0) parts.push(`DEFAULT ${d.pick(kind.defaults)}`);
			}
			if (kind?.plain && d.chance(0.06) && !hasDefault) parts.push('UNIQUE');
			if (kind?.checks && !hasDefault && d.chance(0.25)) parts.push(`CHECK (${d.pick(kind.checks).replaceAll('{c}', column)})`);
			lines.push(parts.join(' '));
			plainFields.push({ name: column, kind, type });
		}
		if (d.chance(0.04)) lines.push(`${claim('computed_value')} integer GENERATED ALWAYS AS (1 + 1) STORED`);
		const references = (parent: Built, key: Field[], fields: Field[], inline: boolean) => {
			const target = `${ident(parent.name)} (${key.map((field) => field.name).join(', ')})`;
			const action = d.pick(['', '', ' ON DELETE CASCADE', ' ON DELETE SET NULL', ' ON DELETE RESTRICT', ' ON UPDATE CASCADE', ' ON DELETE NO ACTION']);
			return inline ? `REFERENCES ${target}${action}` : `FOREIGN KEY (${fields.map((field) => field.name).join(', ')}) REFERENCES ${target}${action}`;
		};
		const links = i === 0 ? 0 : d.pick([0, 1, 1, 1, 2, 3]);
		const attach = (parent: Built, via: Dice) => {
			const key = via.pick(parent.keys);
			const nullable = via.chance(0.45);
			const fields = key.map((field) => {
				const length = /^(varchar|char)\((\d+)\)$/.exec(field.type);
				const type = length && via.chance(0.4) ? `${length[1]}(${via.pick([Number(length[2]), Number(length[2]) + 10, 3, 1].filter((n) => n > 0))})` : field.type;
				return { name: claim(`${parent.name.replace(/[^a-z0-9_]/gi, '_').toLowerCase()}_${field.name}`), type };
			});
			if (fields.length === 1 && via.chance(0.6)) {
				const only = fields[0] as Field;
				lines.push(`${only.name} ${only.type}${nullable ? '' : ' NOT NULL'} ${references(parent, key, fields, true)}`);
			} else {
				for (const field of fields) lines.push(`${field.name} ${field.type}${nullable ? '' : ' NOT NULL'}`);
				lines.push(references(parent, key, fields, false));
			}
		};
		const parents = built.filter((candidate) => candidate.keys.length > 0);
		for (let k = 0; k < links && parents.length > 0; k++) attach(d.pick(parents), d);
		if (d.chance(0.1) && keys.length > 0) attach({ name, keys }, d);
		out.push(`CREATE TABLE ${ident(name)} (\n  ${lines.join(',\n  ')}\n)`);
		const own = ident(name);
		const simple = plainFields.filter((field) => field.kind?.plain);
		if (simple.length > 0 && d.chance(0.25)) pending.push(`CREATE INDEX ON ${own} (${(d.pick(simple) as { name: string }).name})`);
		if (simple.length >= 2 && d.chance(0.1)) pending.push(`CREATE UNIQUE INDEX ON ${own} (${d.shuffle(simple).slice(0, 2).map((field) => field.name).join(', ')})`);
		built.push({ name, keys });
	}
	const holders = built.filter((candidate) => candidate.keys.length > 0);
	if (built.length >= 2 && holders.length >= 1 && d.chance(0.2)) {
		const from = d.pick(built);
		const targets = holders.filter((candidate) => candidate !== from);
		const to = targets.length > 0 ? d.pick(targets) : null;
		if (to) {
			const key = d.pick(to.keys);
			const nullable = d.chance(0.7);
			const columns = key.map((field, index) => ({ name: `back_${index}_${field.name}`, type: field.type }));
			for (const column of columns) pending.push(`ALTER TABLE ${ident(from.name)} ADD COLUMN ${column.name} ${column.type}${nullable ? '' : ' NOT NULL'}`);
			pending.push(`ALTER TABLE ${ident(from.name)} ADD FOREIGN KEY (${columns.map((column) => column.name).join(', ')}) REFERENCES ${ident(to.name)} (${key.map((field) => field.name).join(', ')})`);
		}
	}
	return `${[...out, ...pending].join(';\n')};\n`;
}
