import { PGlite } from '@electric-sql/pglite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { schemaflowUiEs } from '../../i18n/schemaflow-ui-es';
import { quote } from '../dialects/names';
import { parseSql } from '../parse/sql-parse';
import { buildSnippets } from './query-snippets';
import { sampleSql, type SkipReason } from './sample-rows';

const texts = schemaflowUiEs.pg.query.snippets;
const q = (name: string) => quote('postgres', name);

let db: PGlite;

beforeAll(async () => {
	db = new PGlite();
	await db.waitReady;
}, 60_000);

afterAll(async () => {
	await db.close();
});

async function attempt(sql: string): Promise<{ code: string | null; rows: number }> {
	await db.exec('SAVEPOINT probe');
	try {
		const results = await db.exec(sql);
		const last = [...results].reverse().find((r) => r.fields.length > 0);
		return { code: null, rows: last?.rows.length ?? 0 };
	} catch (error) {
		return { code: (error as { code?: string }).code ?? 'none', rows: 0 };
	} finally {
		await db.exec('ROLLBACK TO SAVEPOINT probe');
	}
}

interface Outcome {
	rows: Record<string, number>;
	reasons: Record<string, SkipReason>;
	failures: string[];
	names: Record<string, string>;
}

async function fillAndAsk(ddl: string): Promise<Outcome> {
	const schema = parseSql('postgres', ddl).schema;
	const result = sampleSql(schema, null, 'es');
	const outcome: Outcome = { rows: {}, reasons: {}, failures: [], names: {} };
	for (const table of schema.tables) {
		outcome.names[table.id] = table.name;
		const reason = result.reasons[table.id];
		if (reason) outcome.reasons[table.name] = reason;
	}
	await db.exec('BEGIN');
	try {
		await db.exec(ddl);
		for (const table of schema.tables.slice(0, 12)) {
			const one = buildSnippets(schema, table.id, texts, 'es').find((snippet) => snippet.id === 'sample');
			const tried = await attempt(one?.sql ?? '');
			if (tried.code) outcome.failures.push(`one table ${table.name}: ${tried.code}`);
		}
		await db.exec(result.sql);
		for (const table of schema.tables) {
			if (result.reasons[table.id]) continue;
			const counted = await db.query<{ n: number }>(`SELECT count(*)::int AS n FROM ${q(table.name)}`);
			outcome.rows[table.name] = counted.rows[0]?.n ?? 0;
			if (counted.rows[0]?.n !== result.rows[table.id]) outcome.failures.push(`${table.name}: ${counted.rows[0]?.n} rows, expected ${result.rows[table.id]}`);
		}
		for (const table of schema.tables) {
			for (const snippet of buildSnippets(schema, table.id, texts, 'es')) {
				if (snippet.id === 'sample' || snippet.id === 'sample-all') continue;
				const tried = await attempt(snippet.sql);
				if (tried.code) outcome.failures.push(`${table.name} ${snippet.id}: ${tried.code}`);
			}
		}
	} finally {
		await db.exec('ROLLBACK');
	}
	return outcome;
}

describe('designs written by hand, not made for the tool', () => {
	it('fills a design with quoted names, identity keys, a self reference and a junction (Chinook style)', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE "Artist" ("ArtistId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(120));
CREATE TABLE "Album" ("AlbumId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" varchar(160) NOT NULL, "ArtistId" integer NOT NULL REFERENCES "Artist" ("ArtistId"));
CREATE TABLE "Genre" ("GenreId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(120));
CREATE TABLE "MediaType" ("MediaTypeId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(120));
CREATE TABLE "Track" ("TrackId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(200) NOT NULL, "AlbumId" integer REFERENCES "Album" ("AlbumId"), "MediaTypeId" integer NOT NULL REFERENCES "MediaType" ("MediaTypeId"), "GenreId" integer REFERENCES "Genre" ("GenreId"), "Composer" varchar(220), "Milliseconds" integer NOT NULL, "Bytes" integer, "UnitPrice" numeric(10,2) NOT NULL);
CREATE TABLE "Playlist" ("PlaylistId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(120));
CREATE TABLE "PlaylistTrack" ("PlaylistId" integer NOT NULL REFERENCES "Playlist" ("PlaylistId"), "TrackId" integer NOT NULL REFERENCES "Track" ("TrackId"), PRIMARY KEY ("PlaylistId", "TrackId"));
CREATE TABLE "Employee" ("EmployeeId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "LastName" varchar(20) NOT NULL, "FirstName" varchar(20) NOT NULL, "Title" varchar(30), "ReportsTo" integer REFERENCES "Employee" ("EmployeeId"), "BirthDate" timestamp, "HireDate" timestamp, "Email" varchar(60));
CREATE TABLE "Customer" ("CustomerId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "FirstName" varchar(40) NOT NULL, "LastName" varchar(20) NOT NULL, "Company" varchar(80), "Email" varchar(60) NOT NULL, "SupportRepId" integer REFERENCES "Employee" ("EmployeeId"));
CREATE TABLE "Invoice" ("InvoiceId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "CustomerId" integer NOT NULL REFERENCES "Customer" ("CustomerId"), "InvoiceDate" timestamp NOT NULL, "Total" numeric(10,2) NOT NULL);
CREATE TABLE "InvoiceLine" ("InvoiceLineId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "InvoiceId" integer NOT NULL REFERENCES "Invoice" ("InvoiceId"), "TrackId" integer NOT NULL REFERENCES "Track" ("TrackId"), "UnitPrice" numeric(10,2) NOT NULL, "Quantity" integer NOT NULL);
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.reasons).toEqual({});
		expect(Object.values(outcome.rows)).toEqual(Array(11).fill(3));
	}, 60_000);

	it('fills a design with an enum, a domain, text arrays, tsvector and defaults, and says which tables a required cycle blocks (Pagila style)', async () => {
		const outcome = await fillAndAsk(`
CREATE TYPE mpaa_rating AS ENUM ('G', 'PG', 'PG-13', 'R', 'NC-17');
CREATE DOMAIN year AS integer CONSTRAINT year_check CHECK (VALUE >= 1901 AND VALUE <= 2155);
CREATE TABLE language (language_id serial PRIMARY KEY, name char(20) NOT NULL, last_update timestamptz NOT NULL DEFAULT now());
CREATE TABLE film (film_id serial PRIMARY KEY, title varchar(255) NOT NULL, description text, release_year year, language_id smallint NOT NULL REFERENCES language (language_id), rental_duration smallint NOT NULL DEFAULT 3, rental_rate numeric(4,2) NOT NULL DEFAULT 4.99, length smallint, replacement_cost numeric(5,2) NOT NULL DEFAULT 19.99, rating mpaa_rating DEFAULT 'G', special_features text[], fulltext tsvector NOT NULL);
CREATE TABLE actor (actor_id serial PRIMARY KEY, first_name varchar(45) NOT NULL, last_name varchar(45) NOT NULL);
CREATE TABLE film_actor (actor_id smallint NOT NULL REFERENCES actor (actor_id), film_id smallint NOT NULL REFERENCES film (film_id), PRIMARY KEY (actor_id, film_id));
CREATE TABLE country (country_id serial PRIMARY KEY, country varchar(50) NOT NULL);
CREATE TABLE city (city_id serial PRIMARY KEY, city varchar(50) NOT NULL, country_id smallint NOT NULL REFERENCES country (country_id));
CREATE TABLE address (address_id serial PRIMARY KEY, address varchar(50) NOT NULL, district varchar(20) NOT NULL, city_id smallint NOT NULL REFERENCES city (city_id), postal_code varchar(10), phone varchar(20) NOT NULL);
CREATE TABLE store (store_id serial PRIMARY KEY, manager_staff_id smallint NOT NULL UNIQUE, address_id smallint NOT NULL REFERENCES address (address_id));
CREATE TABLE staff (staff_id serial PRIMARY KEY, first_name varchar(45) NOT NULL, last_name varchar(45) NOT NULL, address_id smallint NOT NULL REFERENCES address (address_id), email varchar(50), store_id smallint NOT NULL, active boolean NOT NULL DEFAULT true, username varchar(16) NOT NULL, picture bytea);
ALTER TABLE store ADD FOREIGN KEY (manager_staff_id) REFERENCES staff (staff_id);
ALTER TABLE staff ADD FOREIGN KEY (store_id) REFERENCES store (store_id);
CREATE TABLE customer (customer_id serial PRIMARY KEY, store_id smallint NOT NULL REFERENCES store (store_id), first_name varchar(45) NOT NULL, last_name varchar(45) NOT NULL, email varchar(50), address_id smallint NOT NULL REFERENCES address (address_id), activebool boolean NOT NULL DEFAULT true, create_date date NOT NULL DEFAULT CURRENT_DATE);
CREATE TABLE inventory (inventory_id serial PRIMARY KEY, film_id smallint NOT NULL REFERENCES film (film_id), store_id smallint NOT NULL REFERENCES store (store_id));
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.reasons).toEqual({ store: 'parent', staff: 'cycle', customer: 'parent', inventory: 'parent' });
		expect(outcome.rows).toMatchObject({ language: 3, film: 3, actor: 3, film_actor: 3, country: 3, city: 3, address: 3 });
	}, 60_000);

	it('fills a design where one foreign key column belongs to two keys (multi-tenant)', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE tenants (id integer PRIMARY KEY, name text NOT NULL);
CREATE TABLE users (tenant_id integer NOT NULL REFERENCES tenants (id), id integer NOT NULL, email text NOT NULL, PRIMARY KEY (tenant_id, id), UNIQUE (tenant_id, email));
CREATE TABLE projects (tenant_id integer NOT NULL REFERENCES tenants (id), id integer NOT NULL, name text NOT NULL, owner_id integer NOT NULL, PRIMARY KEY (tenant_id, id), FOREIGN KEY (tenant_id, owner_id) REFERENCES users (tenant_id, id));
CREATE TABLE tasks (tenant_id integer NOT NULL, id integer NOT NULL, project_id integer NOT NULL, assignee_id integer, title text NOT NULL, PRIMARY KEY (tenant_id, id), FOREIGN KEY (tenant_id, project_id) REFERENCES projects (tenant_id, id), FOREIGN KEY (tenant_id, assignee_id) REFERENCES users (tenant_id, id));
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.rows).toEqual({ tenants: 3, users: 3, projects: 3, tasks: 3 });
	}, 60_000);

	it('fills a design whose key is a natural code and whose foreign keys point to unique columns, not to the key', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE countries (code char(2) PRIMARY KEY, name varchar(60) NOT NULL UNIQUE);
CREATE TABLE currencies (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, iso char(3) NOT NULL UNIQUE, country_code char(2) REFERENCES countries (code));
CREATE TABLE prices (sku varchar(20) NOT NULL, currency_iso char(3) NOT NULL REFERENCES currencies (iso), amount numeric(8,2) NOT NULL CHECK (amount >= 0), PRIMARY KEY (sku, currency_iso));
CREATE TABLE tags (name varchar(5) NOT NULL UNIQUE, active boolean NOT NULL UNIQUE);
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.rows).toEqual({ countries: 3, currencies: 3, prices: 3, tags: 2 });
	}, 60_000);

	it('breaks a cycle at the optional key and fills both tables', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE departments (id integer PRIMARY KEY, name text NOT NULL, manager_id integer);
CREATE TABLE employees (id integer PRIMARY KEY, name text NOT NULL, department_id integer NOT NULL REFERENCES departments (id));
ALTER TABLE departments ADD FOREIGN KEY (manager_id) REFERENCES employees (id);
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.reasons).toEqual({});
		expect(outcome.rows).toEqual({ departments: 3, employees: 3 });
	}, 60_000);

	it('fills a table whose required key points to itself and one whose computed column is unique', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE roots (id integer PRIMARY KEY, parent_id integer NOT NULL REFERENCES roots (id));
CREATE TABLE codes (id integer PRIMARY KEY, label text NOT NULL, slug text GENERATED ALWAYS AS (lower(label)) STORED UNIQUE);
CREATE TABLE pinned (id integer PRIMARY KEY, code text GENERATED ALWAYS AS ('fixed') STORED UNIQUE);
CREATE TABLE tied (id integer PRIMARY KEY, code text GENERATED ALWAYS AS ('fixed') STORED UNIQUE);
CREATE TABLE ties (id integer PRIMARY KEY, tied_code text NOT NULL REFERENCES tied (code));
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.reasons).toEqual({ tied: 'generated-key', ties: 'parent' });
		expect(outcome.rows).toMatchObject({ roots: 3, codes: 1, pinned: 1 });
	}, 60_000);

	it('writes the values the checks ask for and keeps working when it cannot', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE products (id integer PRIMARY KEY, name varchar(40) NOT NULL CHECK (char_length(name) >= 3), price numeric(8,2) NOT NULL CHECK (price > 100), stock integer NOT NULL, sold integer NOT NULL, status text NOT NULL CHECK (status IN ('new', 'used', 'broken')), starts_at date NOT NULL, ends_at date NOT NULL, CHECK (sold <= stock), CHECK (ends_at > starts_at));
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.rows).toEqual({ products: 3 });
		const ean = parseSql('postgres', "CREATE TABLE codes (id integer PRIMARY KEY, ean varchar(20) NOT NULL CHECK (ean ~ '^[0-9]{13}$'));").schema;
		await db.exec('BEGIN');
		try {
			await db.exec("CREATE TABLE codes (id integer PRIMARY KEY, ean varchar(20) NOT NULL CHECK (ean ~ '^[0-9]{13}$'));");
			expect((await attempt(sampleSql(ean, null, 'es').sql)).code).toBe('23514');
		} finally {
			await db.exec('ROLLBACK');
		}
	}, 60_000);

	it('fits tiny decimals, wide bit strings and columns that allow only a few distinct values', async () => {
		const outcome = await fillAndAsk(`
CREATE TABLE odd_numbers (id integer PRIMARY KEY, a numeric(2,3) NOT NULL, b numeric(1,1) NOT NULL, c numeric(1,0) NOT NULL, d bit(20) NOT NULL, e smallint NOT NULL UNIQUE, f numeric(4,2) UNIQUE NOT NULL, g char(1) NOT NULL UNIQUE);
`);
		expect(outcome.failures).toEqual([]);
		expect(outcome.rows).toEqual({ odd_numbers: 3 });
	}, 60_000);

	it('keeps identity sequences right even when the names are longer than PostgreSQL allows', async () => {
		const name = `${'c_'.repeat(40)}id`;
		const outcome = await fillAndAsk(`CREATE TABLE long_names (${name} integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, label text);`);
		expect(outcome.failures).toEqual([]);
	}, 60_000);
});

describe('ready-made queries that change data', () => {
	const ddl = `
CREATE TABLE owners (id integer PRIMARY KEY, name text NOT NULL);
CREATE TABLE pets (id integer PRIMARY KEY, owner_id integer NOT NULL REFERENCES owners (id) ON DELETE SET NULL, name text NOT NULL);
CREATE TABLE badges (id integer PRIMARY KEY, label text NOT NULL);
CREATE TABLE awards (id integer PRIMARY KEY, badge_id integer REFERENCES badges (id) ON DELETE SET NULL, note text);
CREATE TABLE guests (id integer PRIMARY KEY, host_id integer REFERENCES guests (id), name text NOT NULL);
CREATE TABLE codes (id integer PRIMARY KEY, code varchar(3) NOT NULL UNIQUE, price numeric(3,2) NOT NULL CHECK (price >= 0), qty integer NOT NULL, total integer GENERATED ALWAYS AS (qty * 2) STORED);
`;
	const schema = parseSql('postgres', ddl).schema;
	const ids = (name: string) => buildSnippets(schema, schema.tables.find((table) => table.name === name)?.id ?? '', texts, 'es').map((snippet) => snippet.id);

	it('offers the removal only where deleting a row cannot break another table', () => {
		expect(ids('owners')).not.toContain('remove');
		expect(ids('guests')).not.toContain('remove');
		for (const name of ['pets', 'badges', 'awards', 'codes']) expect(ids(name), name).toContain('remove');
	});

	it('changes a column that no key, check or generated value depends on', () => {
		const codes = schema.tables.find((table) => table.name === 'codes');
		const update = buildSnippets(schema, codes?.id ?? '', texts, 'es').find((snippet) => snippet.id === 'update');
		expect(update?.sql).toContain('SET qty =');
	});

	it('runs every one of them after the sample rows are in', async () => {
		const outcome = await fillAndAsk(ddl);
		expect(outcome.failures).toEqual([]);
	}, 60_000);
});
