import { PGlite } from '@electric-sql/pglite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { schemaflowUiEs } from '../../i18n/schemaflow-ui-es';
import { quote } from '../dialects/names';
import { generateSql } from '../dialects/sql-generate';
import { parseSql } from '../parse/sql-parse';
import { randomSchema, type Family } from '../testing-random';
import { randomSql } from '../testing-sql';
import { buildSnippets } from './query-snippets';
import type { Relation, Schema, Table } from '../model/types';
import { sampleSql, SKIP_REASONS, type SkipReason } from './sample-rows';

const COUNT = Number(process.env.SF_FUZZ ?? 60);
const FIRST = Number(process.env.SF_FUZZ_FROM ?? 1);
const TABLES = Number(process.env.SF_FUZZ_TABLES ?? 4);
type Kind = Family | 'typed';

const FAMILIES: Kind[] = (process.env.SF_FUZZ_FAMILIES ?? 'plausible,hostile,checks,typed,session').split(',') as Kind[];
const texts = schemaflowUiEs.pg.query.snippets;

const MINIMUM_FILLED: Record<Kind, number> = { plausible: 1, hostile: 0.6, checks: 0.9, typed: 0.6, session: 0.7 };

let db: PGlite;

beforeAll(async () => {
	db = new PGlite();
	await db.waitReady;
}, 60_000);

afterAll(async () => {
	await db.close();
});

async function attempt(sql: string): Promise<{ error: string | null; rows: number }> {
	await db.exec('SAVEPOINT probe');
	try {
		const results = await db.exec(sql);
		const last = [...results].reverse().find((r) => r.fields.length > 0);
		return { error: null, rows: last?.rows.length ?? 0 };
	} catch (error) {
		const e = error as { code?: string; message?: string; detail?: string };
		return { error: `${e.code ?? 'none'} ${String(e.message ?? error).slice(0, 140)}${e.detail ? ` (${e.detail.slice(0, 80)})` : ''}`, rows: 0 };
	} finally {
		await db.exec('ROLLBACK TO SAVEPOINT probe');
	}
}

const mandatory = (table: Table, id: string) => {
	const column = table.columns.find((candidate) => candidate.id === id);
	return column !== undefined && (!column.nullable || table.primaryKey.includes(id));
};

function justified(schema: Schema, table: Table, reason: SkipReason, reasons: Record<string, SkipReason>): boolean {
	const required = (relation: Relation) => {
		const from = schema.tables.find((candidate) => candidate.id === relation.fromTable);
		return from !== undefined && relation.fromTable !== relation.toTable && relation.fromColumns.every((id) => mandatory(from, id));
	};
	const mine = schema.relations.filter((relation) => relation.fromTable === table.id && required(relation));
	if (reason === 'unknown-type') return table.columns.some((column) => column.type.kind === 'raw');
	if (reason === 'generated-key') return table.columns.some((column) => column.default.kind === 'computed');
	if (reason === 'parent') {
		return mine.some((relation) => {
			const parent = schema.tables.find((candidate) => candidate.id === relation.toTable);
			return reasons[relation.toTable] !== undefined || (parent !== undefined && relation.toColumns.some((id) => !mandatory(parent, id)));
		});
	}
	const reaches = (from: string, goal: string, seen = new Set<string>()): boolean => {
		if (from === goal) return true;
		if (seen.has(from)) return false;
		seen.add(from);
		return schema.relations.some((relation) => relation.fromTable === from && required(relation) && reaches(relation.toTable, goal, seen));
	};
	return mine.some((relation) => reaches(relation.toTable, table.id));
}

function design(kind: Kind, seed: number): { schema: Schema; ddl: string; blocked: boolean } {
	if (kind === 'typed') {
		const ddl = randomSql(seed);
		const parsed = parseSql('postgres', ddl);
		return { schema: parsed.schema, ddl, blocked: parsed.issues.some((issue) => issue.blocking) };
	}
	const schema = randomSchema(kind, seed);
	const ddl = generateSql('postgres', schema);
	return { schema, ddl: seed % 2 === 0 ? ddl.replaceAll('GENERATED BY DEFAULT AS IDENTITY', 'GENERATED ALWAYS AS IDENTITY') : ddl, blocked: false };
}

describe.each(FAMILIES)('random designs (%s)', (family) => {
	it(`fills the tables and runs every ready-made query on ${COUNT} designs`, async () => {
		const failures: string[] = [];
		const stats = { designs: 0, blocked: 0, invalid: 0, tables: 0, filled: 0, rows: [0, 0, 0, 0], reasons: Object.fromEntries(SKIP_REASONS.map((reason) => [reason, 0])) as Record<string, number> };
		for (let seed = FIRST; seed < FIRST + COUNT; seed++) {
			const { schema, ddl, blocked } = design(family, seed);
			const where = `${family}#${seed}`;
			if (blocked) {
				stats.blocked++;
				continue;
			}
			await db.exec('BEGIN');
			try {
				try {
					await db.exec(ddl);
				} catch (error) {
					if (family === 'session') stats.invalid++;
					else failures.push(`${where} DDL: ${String((error as Error).message).slice(0, 140)}`);
					continue;
				}
				stats.designs++;
				stats.tables += schema.tables.length;
				const result = sampleSql(schema, null, 'es');
				for (const each of schema.tables) {
					const reason = result.reasons[each.id];
					if (reason === undefined) {
						stats.filled++;
						stats.rows[Math.min(result.rows[each.id] ?? 0, 3)]!++;
						continue;
					}
					if (!SKIP_REASONS.includes(reason)) failures.push(`${where} skipped ${each.name} without a valid reason (${reason})`);
					else if (!justified(schema, each, reason, result.reasons)) failures.push(`${where} skipped ${each.name} (${reason}) without need`);
					stats.reasons[reason]!++;
					if (family === 'plausible') failures.push(`${where} skipped ${each.name} (${reason}) in a design the interface builds`);
				}

				for (const table of schema.tables.slice(0, TABLES)) {
					const snippet = buildSnippets(schema, table.id, texts, 'es').find((s) => s.id === 'sample');
					const one = await attempt(snippet?.sql ?? '');
					if (one.error) failures.push(`${where} one table (${table.name}): ${one.error}`);
				}

				await db.exec('SAVEPOINT whole');
				try {
					await db.exec(result.sql);
				} catch (error) {
					const e = error as { code?: string; message?: string; detail?: string };
					failures.push(`${where} all tables: ${e.code ?? 'none'} ${String(e.message).slice(0, 140)} (${(e.detail ?? '').slice(0, 80)})`);
					await db.exec('ROLLBACK TO SAVEPOINT whole');
					continue;
				}

				for (const table of schema.tables) {
					if (result.reasons[table.id] !== undefined) continue;
					const counted = await db.query<{ n: number }>(`SELECT count(*)::int AS n FROM ${quote('postgres', table.name)}`);
					const expected = result.rows[table.id];
					if (counted.rows[0]?.n !== expected || !expected) failures.push(`${where} ${table.name}: ${counted.rows[0]?.n} rows, expected ${expected}`);
				}

				for (const table of schema.tables.slice(0, TABLES)) {
					for (const snippet of buildSnippets(schema, table.id, texts, 'es')) {
						if (snippet.id === 'sample' || snippet.id === 'sample-all') continue;
						const run = await attempt(snippet.sql);
						if (run.error) failures.push(`${where} ${table.name} «${snippet.id}»: ${run.error}`);
						else if (snippet.id === 'rows' && run.rows === 0 && table.columns.length > 0 && result.reasons[table.id] === undefined) failures.push(`${where} ${table.name} «rows» returned nothing`);
					}
				}
			} finally {
				await db.exec('ROLLBACK');
			}
		}
		if (process.env.SF_FUZZ_STATS) console.log(`[${family}] ${JSON.stringify(stats)}`);
		expect({ filled: stats.filled / Math.max(1, stats.tables) >= MINIMUM_FILLED[family], parsed: stats.blocked <= COUNT * 0.1 && stats.invalid <= COUNT * 0.5, failures: failures.slice(0, 15), failureCount: failures.length }).toMatchObject({ filled: true, parsed: true, failures: [], failureCount: 0 });
	}, 900_000);
});
