import { readFileSync } from 'node:fs';
import { TOOLS, HERO_TOOLS } from './catalog.mjs';
const paths = JSON.parse(readFileSync('./brand-paths.json', 'utf8'));
const missing = TOOLS.filter(([s]) => !paths[s]).map(([s]) => s);
const heroMissing = HERO_TOOLS.filter((s) => !paths[s]);
const byArea = {};
for (const [, , a] of TOOLS) byArea[a] = (byArea[a] || 0) + 1;
console.log('tools:', TOOLS.length, '| sin path:', missing.join(' ') || 'ninguno');
console.log('hero sin path:', heroMissing.join(' ') || 'ninguno');
console.log('por área:', JSON.stringify(byArea));
