/** Writes src/lib/components/OrgMark.svelte with the three employer marks. */
import { writeFileSync } from 'node:fs';
import { KAIZEN_MARK, STARCARGO_MARK } from './logos.mjs';

const strip = (svg) => svg.replace(/^<svg /, '<svg ').trim();

const out = `<script lang="ts">
	/**
	 * Employer marks, taken from each company's own repository and rendered in
	 * ink. Inter Cargo only ships a colour PNG, so it is masked rather than
	 * placed as an image — otherwise the strip would import a brand palette and
	 * break the rule that a hue on this site always means an area.
	 *
	 * Generated by design/emit-orgmark.mjs — do not edit the paths by hand.
	 */
	let { org, width = 140 }: { org: 'intercargo' | 'kaizen' | 'starcargo'; width?: number } =
		$props();
</script>

{#if org === 'intercargo'}
	<span class="mark intercargo" style="--w: {width}px"></span>
{:else if org === 'kaizen'}
	<span class="mark kaizen" style="--w: {width}px">
		${strip(KAIZEN_MARK)}
	</span>
{:else}
	<span class="mark starcargo" style="--w: {width}px">
		${strip(STARCARGO_MARK)}
	</span>
{/if}

<style>
	.mark {
		display: flex;
		align-items: center;
		color: var(--ink-muted);
		transition: color 160ms ease;
	}

	.mark :global(svg) {
		max-width: 100%;
		height: auto;
	}

	.kaizen :global(svg) {
		width: 1.875rem;
		height: 1.875rem;
	}

	.starcargo :global(svg) {
		width: var(--w);
	}

	.intercargo {
		width: var(--w);
		height: 1.625rem;
		background: currentColor;
		-webkit-mask: url('/img/brand/intercargo-logo.png') left center / contain no-repeat;
		mask: url('/img/brand/intercargo-logo.png') left center / contain no-repeat;
	}
</style>
`;

writeFileSync('../src/lib/components/OrgMark.svelte', out);
console.log('OrgMark.svelte written —', out.length, 'bytes');
