/**
 * Writes src/lib/brands.ts from the icon data used by the canvas, so the site
 * and the design canvas cannot drift apart.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { HERO_TOOLS, TOOLS } from './catalog.mjs';

const PATHS = JSON.parse(readFileSync('./brand-paths.json', 'utf8'));

const entries = TOOLS.map(([slug, label, area]) => {
	const d = PATHS[slug]?.d ?? null;
	return { slug, label, area, d };
});

const monogram = (label) =>
	label
		.replace(/[^A-Za-z ]/g, '')
		.split(' ')
		.filter(Boolean)
		.map((w) => w[0])
		.join('')
		.slice(0, 2)
		.toUpperCase();

const lines = entries.map(
	(t) =>
		`\t{\n\t\tslug: '${t.slug}',\n\t\tlabel: '${t.label.replace(/'/g, "\\'")}',\n\t\tarea: '${t.area}',\n\t\tmonogram: '${monogram(t.label)}',\n\t\td: ${t.d ? `'${t.d}'` : 'null'}\n\t}`
);

const out = `// Generated by design/emit-brands.mjs — do not edit by hand.
// Brand marks come from simple-icons (CC0). They are rendered in ink, never in
// brand colour: on this site a hue only ever means an area.
import type { AreaId } from './areas';

export type Tool = {
	slug: string;
	label: string;
	area: AreaId;
	/** Shown when simple-icons carries no mark for the tool. */
	monogram: string;
	/** 24x24 path, or null when there is no mark. */
	d: string | null;
};

export const TOOLS: Tool[] = [
${lines.join(',\n')}
];

/** The tools the current work actually runs on — used for the home hero strip. */
export const HERO_TOOLS: string[] = ${JSON.stringify(HERO_TOOLS)};

export const heroTools = (): Tool[] =>
	HERO_TOOLS.map((slug) => TOOLS.find((t) => t.slug === slug)).filter(
		(t): t is Tool => Boolean(t)
	);

export const toolsByArea = (): Record<string, number> => {
	const counts: Record<string, number> = {};
	for (const tool of TOOLS) counts[tool.area] = (counts[tool.area] ?? 0) + 1;
	return counts;
};
`;

writeFileSync('../src/lib/brands.ts', out);
console.log('src/lib/brands.ts written —', entries.length, 'tools,', out.length, 'bytes');
