/**
 * Writes src/lib/brands.ts. Two things come out of one source:
 *   TOOLS  — the 33 curated marks that fill the home tool grid
 *   BRANDS — the full brand library, so any stack string in a project can
 *            resolve to a real mark, not just the 33 on the grid
 * so the site and the design canvas cannot drift apart.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { HERO_TOOLS, TOOLS } from './catalog.mjs';

const LIB = JSON.parse(readFileSync('./brand-library.json', 'utf8'));

const monogram = (label) =>
	label
		.replace(/[^A-Za-z ]/g, '')
		.split(' ')
		.filter(Boolean)
		.map((w) => w[0])
		.join('')
		.slice(0, 2)
		.toUpperCase();

const gridEntries = TOOLS.map(([slug, label, area]) => ({
	slug,
	label,
	area,
	d: LIB[slug]?.d ?? null
}));

const missing = gridEntries.filter((t) => !t.d).map((t) => t.slug);
if (missing.length) {
	console.warn('[emit-brands] grid tools with no mark:', missing.join(', '));
}

const toolLine = (t) =>
	`\t{\n\t\tslug: '${t.slug}',\n\t\tlabel: '${t.label.replace(/'/g, "\\'")}',\n\t\tarea: '${t.area}',\n\t\tmonogram: '${monogram(t.label)}',\n\t\td: ${t.d ? `'${t.d}'` : 'null'}\n\t}`;

// The library keyed by slug — every mark available to a stack list.
const brandLines = Object.entries(LIB)
	.filter(([, v]) => v.d)
	.map(([slug, v]) => `\t${slug}: '${v.d}'`);

const out = `// Generated by design/emit-brands.mjs — do not edit by hand.
// Brand marks come from simple-icons (CC0); Playwright is from simple-icons
// v12, before it was withdrawn over trademark. They are rendered in ink, never
// in brand colour: on this site a hue only ever means an area.
import type { AreaId } from './areas';

export type Tool = {
	slug: string;
	label: string;
	area: AreaId;
	/** Shown when there is no mark for the tool. */
	monogram: string;
	/** 24x24 path, or null when there is no mark. */
	d: string | null;
};

/** The curated grid — 33 tools, area-tagged, shown on the home page. */
export const TOOLS: Tool[] = [
${gridEntries.map(toolLine).join(',\n')}
];

/** Full brand library, keyed by slug — every mark a stack list can resolve. */
export const BRANDS: Record<string, string> = {
${brandLines.join(',\n')}
};

/** The tools the current work actually runs on — used for the home hero strip. */
export const HERO_TOOLS: string[] = ${JSON.stringify(HERO_TOOLS)};

export const heroTools = (): Tool[] =>
	HERO_TOOLS.map((slug) => TOOLS.find((t) => t.slug === slug)).filter(
		(t): t is Tool => Boolean(t)
	);

export const toolsByArea = (): Record<string, number> => {
	const counts: Record<string, number> = {};
	for (const tool of TOOLS) counts[tool.area] = (counts[tool.area] ?? 0) + 1;
	return counts;
};
`;

writeFileSync('../src/lib/brands.ts', out);
console.log(
	'src/lib/brands.ts written —',
	gridEntries.length,
	'grid tools,',
	brandLines.length,
	'library marks,',
	out.length,
	'bytes'
);
