import { PGlite } from '@electric-sql/pglite';
import { describe, expect, it } from 'vitest';
import { diffSchemas, isEmptyDiff } from '../model/diff';
import type { Schema } from '../model/types';
import { parseSql } from '../parse/sql-parse';
import { buildMigration, migrate, migrationWarnings, renderMigration, type Warning } from './migrate';
import { generateSql } from './sql-generate';

const parse = (sql: string): Schema => parseSql('postgres', sql).schema;
const render = (m: ReturnType<typeof migrate>, transaction = false) => renderMigration(m, { transaction, describe: (w: Warning) => w.code });

async function catalog(db: PGlite): Promise<string[]> {
	const columns = await db.query<Record<string, unknown>>(
		`SELECT table_name, column_name, data_type, character_maximum_length, numeric_precision, numeric_scale, is_nullable, column_default, is_identity, identity_generation
		 FROM information_schema.columns WHERE table_schema = 'public' ORDER BY table_name, column_name`
	);
	const constraints = await db.query<Record<string, unknown>>(
		`SELECT c.relname AS t, con.contype AS k, pg_get_constraintdef(con.oid) AS def
		 FROM pg_constraint con JOIN pg_class c ON c.oid = con.conrelid WHERE c.relnamespace = 'public'::regnamespace`
	);
	const indexes = await db.query<Record<string, unknown>>(
		`SELECT tablename AS t, regexp_replace(indexdef, 'INDEX \\S+ ON', 'INDEX ON') AS def FROM pg_indexes
		 WHERE schemaname = 'public' AND indexname NOT IN (SELECT conname FROM pg_constraint)`
	);
	const comments = await db.query<Record<string, unknown>>(
		`SELECT c.relname AS t, a.attname AS col, d.description AS text
		 FROM pg_description d JOIN pg_class c ON c.oid = d.objoid AND c.relnamespace = 'public'::regnamespace
		 LEFT JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.objsubid AND d.objsubid > 0 WHERE c.relkind = 'r'`
	);
	const lines = [
		...columns.rows.map((r) => `col ${JSON.stringify(r)}`),
		...constraints.rows.map((r) => `con ${r.t} ${r.k} ${r.def}`),
		...indexes.rows.map((r) => `idx ${r.t} ${r.def}`),
		...comments.rows.map((r) => `cmt ${r.t} ${r.col ?? ''} ${r.text}`)
	];
	return lines.sort();
}

async function run(sql: string): Promise<string[]> {
	const db = new PGlite();
	try {
		await db.exec(sql);
		return await catalog(db);
	} finally {
		await db.close();
	}
}

async function applied(before: Schema, up: string): Promise<string[]> {
	const db = new PGlite();
	try {
		await db.exec(generateSql('postgres', before));
		await db.exec(up);
		return await catalog(db);
	} finally {
		await db.close();
	}
}

const BASE = `
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(100) NOT NULL UNIQUE, age INTEGER, bio TEXT);
CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, title VARCHAR(200) NOT NULL, views INTEGER DEFAULT 0, price NUMERIC(10, 2), created TIMESTAMP DEFAULT now());
ALTER TABLE posts ADD CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
CREATE INDEX ix_posts_title ON posts (title);
`;

const SCENARIOS: Record<string, [string, string]> = {
	'adds a table with a foreign key and an index': [
		BASE,
		`${BASE}
CREATE TABLE comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL, body TEXT NOT NULL);
CREATE INDEX ix_comments_post ON comments (post_id);
ALTER TABLE comments ADD CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE SET NULL;`
	],
	'drops a table that another table references': [
		BASE,
		`CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(100) NOT NULL UNIQUE, age INTEGER, bio TEXT);`
	],
	'adds and drops columns': [
		BASE,
		BASE.replace('bio TEXT', 'nickname VARCHAR(30) NOT NULL DEFAULT \'x\', score INTEGER').replace('price NUMERIC(10, 2), ', '')
	],
	'changes types, including ones that need a conversion': [
		BASE,
		BASE.replace('age INTEGER', 'age BIGINT')
			.replace('VARCHAR(100)', 'VARCHAR(250)')
			.replace('views INTEGER DEFAULT 0', 'views VARCHAR(20) DEFAULT \'0\'')
			.replace('NUMERIC(10, 2)', 'NUMERIC(12, 4)')
			.replace('created TIMESTAMP DEFAULT now()', 'created TIMESTAMPTZ DEFAULT now()')
	],
	'changes nullability and defaults': [
		BASE,
		BASE.replace('age INTEGER', 'age INTEGER NOT NULL DEFAULT 18').replace('title VARCHAR(200) NOT NULL', 'title VARCHAR(200)').replace('views INTEGER DEFAULT 0', 'views INTEGER DEFAULT 5').replace('created TIMESTAMP DEFAULT now()', 'created TIMESTAMP')
	],
	'changes the primary key': [
		BASE,
		BASE.replace('CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,', 'CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY,').replace('created TIMESTAMP DEFAULT now())', 'created TIMESTAMP DEFAULT now(), PRIMARY KEY (id, user_id))')
	],
	'adds and drops unique constraints and indexes': [
		BASE,
		BASE.replace('email VARCHAR(100) NOT NULL UNIQUE', 'email VARCHAR(100) NOT NULL, UNIQUE (email, age)').replace('CREATE INDEX ix_posts_title ON posts (title);', 'CREATE UNIQUE INDEX ix_posts_user_title ON posts (user_id, title);')
	],
	'changes the actions of a foreign key': [BASE, BASE.replace('ON DELETE CASCADE', 'ON DELETE RESTRICT ON UPDATE CASCADE')],
	'drops a foreign key': [BASE, BASE.replace(/ALTER TABLE posts ADD CONSTRAINT fk_posts_user[^;]*;/, '')],
	'drops a column used by a foreign key and an index': [
		BASE,
		BASE.replace('user_id BIGINT NOT NULL, ', '').replace(/ALTER TABLE posts ADD CONSTRAINT fk_posts_user[^;]*;/, '')
	],
	'turns identity on and off': [
		BASE,
		BASE.replace('CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'CREATE TABLE users (id BIGINT PRIMARY KEY').replace('CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'CREATE TABLE posts (id BIGINT PRIMARY KEY')
	],
	'drops a parent and its child together, whatever their order in the design': [
		`CREATE TABLE users (id BIGINT PRIMARY KEY);
CREATE TABLE posts (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL);
CREATE TABLE comments (id BIGINT PRIMARY KEY, post_id BIGINT NOT NULL, user_id BIGINT);
ALTER TABLE posts ADD CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE comments ADD CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id);
ALTER TABLE comments ADD CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id);`,
		''
	],
	'drops tables that reference each other': [
		`CREATE TABLE a (id INT PRIMARY KEY, b_id INT);
CREATE TABLE b (id INT PRIMARY KEY, a_id INT);
ALTER TABLE a ADD CONSTRAINT fk_a_b FOREIGN KEY (b_id) REFERENCES b (id);
ALTER TABLE b ADD CONSTRAINT fk_b_a FOREIGN KEY (a_id) REFERENCES a (id);`,
		`CREATE TABLE keep (id INT PRIMARY KEY);`
	],
	'drops a table that references itself': [
		`CREATE TABLE node (id INT PRIMARY KEY, parent_id INT);
ALTER TABLE node ADD CONSTRAINT fk_node_parent FOREIGN KEY (parent_id) REFERENCES node (id);`,
		''
	],
	'changes comments': [
		`${BASE}\nCOMMENT ON TABLE users IS 'old'; COMMENT ON COLUMN users.email IS 'mail';`,
		`${BASE}\nCOMMENT ON TABLE users IS 'new'; COMMENT ON COLUMN users.age IS 'years';`
	]
};

describe('PostgreSQL migrations run on a real engine', () => {
	for (const [name, [beforeSql, afterSql]] of Object.entries(SCENARIOS)) {
		it(name, async () => {
			const before = parse(beforeSql);
			const after = parse(afterSql);
			const up = render(migrate('postgres', before, after), true);
			expect(up.length).toBeGreaterThan(0);
			expect(await applied(before, up)).toEqual(await run(generateSql('postgres', after)));
			const down = render(migrate('postgres', after, before), true);
			expect(await applied(after, down)).toEqual(await run(generateSql('postgres', before)));
		}, 60_000);
	}

	it('renames tables and columns when the design keeps its ids', async () => {
		const before = parse(BASE);
		const after: Schema = JSON.parse(JSON.stringify(before));
		const posts = after.tables.find((t) => t.name === 'posts');
		if (!posts) throw new Error('fixture');
		posts.name = 'articles';
		const title = posts.columns.find((c) => c.name === 'title');
		if (!title) throw new Error('fixture');
		title.name = 'headline';
		const diff = diffSchemas(before, after);
		expect(diff.tablesAdded).toHaveLength(0);
		expect(diff.tablesDropped).toHaveLength(0);
		const up = render(migrate('postgres', before, after), true);
		expect(up).toContain('RENAME TO articles');
		expect(up).toContain('RENAME COLUMN title TO headline');
		expect(await applied(before, up)).toEqual(await run(generateSql('postgres', after)));
	}, 60_000);

	it('keeps rows when a column is renamed', async () => {
		const before = parse('CREATE TABLE t (id INTEGER PRIMARY KEY, name VARCHAR(20));');
		const after: Schema = JSON.parse(JSON.stringify(before));
		const column = after.tables[0]?.columns[1];
		if (!column) throw new Error('fixture');
		column.name = 'label';
		const db = new PGlite();
		try {
			await db.exec(generateSql('postgres', before));
			await db.exec("INSERT INTO t VALUES (1, 'kept');");
			await db.exec(render(migrate('postgres', before, after)));
			expect((await db.query<{ label: string }>('SELECT label FROM t')).rows).toEqual([{ label: 'kept' }]);
		} finally {
			await db.close();
		}
	}, 60_000);

	it('is empty when nothing changed, and reversible in the diff', () => {
		const schema = parse(BASE);
		expect(isEmptyDiff(diffSchemas(schema, parse(BASE)))).toBe(true);
		expect(migrate('postgres', schema, parse(BASE)).steps).toHaveLength(0);
	});
});

describe('migration comments', () => {
	it('keeps a hostile name inside its comment line and its quotes', () => {
		const hostile = 'evil\r\nDROP TABLE users;--\u2028DROP DATABASE prod;';
		const full = parse('CREATE TABLE users (id INT PRIMARY KEY); CREATE TABLE keep (id INT PRIMARY KEY, note TEXT);');
		const named: Schema = JSON.parse(JSON.stringify(full));
		const victim = named.tables[1];
		const note = victim?.columns[1];
		if (!victim || !note) throw new Error('fixture');
		victim.name = hostile;
		note.name = hostile;
		const withoutTable: Schema = { ...named, tables: named.tables.filter((t) => t !== victim), relations: [] };
		const withoutColumn: Schema = JSON.parse(JSON.stringify(named));
		const kept = withoutColumn.tables[1];
		if (!kept) throw new Error('fixture');
		kept.columns = kept.columns.filter((c) => c.name !== hostile);
		const inert = (sql: string) =>
			sql
				.replace(/"(?:[^"]|"")*"/g, '""')
				.replace(/`(?:[^`]|``)*`/g, '``')
				.replace(/\[(?:[^\]]|\]\])*\]/g, '[]')
				.replace(/N?'(?:[^']|'')*'/g, "''");
		for (const dialect of ['postgres', 'mysql', 'sqlserver'] as const) {
			for (const [from, to] of [[named, withoutTable], [named, withoutColumn], [withoutTable, named]] as const) {
				const m = migrate(dialect, from, to);
				const sql = renderMigration(m, { transaction: false, describe: (w: Warning) => `${w.code} ${w.table} ${w.column ?? ''}` });
				const lines = sql.split(/\r\n|\r|\n|\u2028|\u2029/);
				expect(lines.filter((line) => line.startsWith('--')), dialect).toHaveLength(migrationWarnings(m).length);
				const executable = inert(lines.filter((line) => !line.startsWith('--')).join('\n'));
				expect(executable, dialect).not.toMatch(/DROP DATABASE/i);
				expect(executable, dialect).not.toMatch(/DROP TABLE users/i);
				expect(executable, dialect).not.toMatch(/prod/i);
			}
		}
	});

	it('writes one comment line per warning', () => {
		const before = parse(BASE);
		const after = parse('CREATE TABLE users (id BIGINT PRIMARY KEY);');
		const m = migrate('postgres', before, after);
		const comments = render(m).split('\n').filter((line) => line.startsWith('--'));
		expect(comments).toHaveLength(migrationWarnings(m).length);
	});
});

describe('migration warnings', () => {
	const warn = (beforeSql: string, afterSql: string) => migrationWarnings(migrate('postgres', parse(beforeSql), parse(afterSql))).map((w) => `${w.level}:${w.code}`);

	it('marks data loss as dangerous', () => {
		expect(warn(BASE, 'CREATE TABLE users (id BIGINT PRIMARY KEY);')).toEqual(expect.arrayContaining(['danger:drop-table', 'danger:drop-column']));
		expect(warn('CREATE TABLE t (id INT PRIMARY KEY, c VARCHAR(200));', 'CREATE TABLE t (id INT PRIMARY KEY, c VARCHAR(20));')).toContain('danger:type-narrow');
		expect(warn('CREATE TABLE t (id INT PRIMARY KEY, c VARCHAR(20));', 'CREATE TABLE t (id INT PRIMARY KEY, c VARCHAR(200));')).toEqual([]);
	});

	it('marks changes that can fail on existing rows as cautions', () => {
		expect(warn('CREATE TABLE t (id INT PRIMARY KEY, c INT);', 'CREATE TABLE t (id INT PRIMARY KEY, c INT NOT NULL);')).toContain('caution:set-not-null');
		expect(warn('CREATE TABLE t (id INT PRIMARY KEY);', 'CREATE TABLE t (id INT PRIMARY KEY, c INT NOT NULL);')).toContain('caution:add-not-null');
		expect(warn('CREATE TABLE t (id INT PRIMARY KEY, c INT);', 'CREATE TABLE t (id INT PRIMARY KEY, c INT UNIQUE);')).toContain('caution:add-unique');
	});
});

describe('migration syntax for the other engines', () => {
	const before = parse('CREATE TABLE t (id INT PRIMARY KEY, name VARCHAR(20) DEFAULT \'a\', old_col INT, UNIQUE (name));');
	const after: Schema = JSON.parse(JSON.stringify(before));
	const table = after.tables[0];
	if (!table) throw new Error('fixture');
	table.columns = table.columns.filter((c) => c.name !== 'old_col');
	const name = table.columns[1];
	if (!name) throw new Error('fixture');
	name.type = { kind: 'varchar', length: 80 };
	name.default = { kind: 'literal', value: 'b' };
	name.nullable = false;
	table.uniques = [];
	table.columns.push({ id: 'newcol', name: 'created', type: { kind: 'timestamp' }, nullable: false, default: { kind: 'now' } });

	it('uses MODIFY COLUMN and DROP INDEX in MySQL', () => {
		const sql = render(buildMigration('mysql', diffSchemas(before, after)));
		expect(sql).toContain("ALTER TABLE t MODIFY COLUMN name VARCHAR(80) NOT NULL DEFAULT 'b';");
		expect(sql).toContain('ALTER TABLE t DROP INDEX name;');
		expect(sql).toContain('ALTER TABLE t DROP COLUMN old_col;');
		expect(sql).toContain('ALTER TABLE t ADD COLUMN created DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);');
		expect(sql).not.toContain('BEGIN');
	});

	it('drops the default constraint by lookup and separates batches in SQL Server', () => {
		const sql = render(buildMigration('sqlserver', diffSchemas(before, after)), true);
		expect(sql).toContain('sys.default_constraints');
		expect(sql).toContain('ALTER TABLE t ALTER COLUMN name NVARCHAR(80) NOT NULL;');
		expect(sql).toContain("ALTER TABLE t ADD DEFAULT N'b' FOR name;");
		expect(sql).toContain('GO');
		expect(sql.startsWith('SET XACT_ABORT ON;\nBEGIN TRANSACTION;')).toBe(true);
		expect(sql.trimEnd().endsWith('COMMIT;')).toBe(true);
	});

	it('names every declared variable once', () => {
		const sql = render(buildMigration('sqlserver', diffSchemas(before, after)));
		const names = [...sql.matchAll(/DECLARE (@m\d+)/g)].map((m) => m[1]);
		expect(new Set(names).size).toBe(names.length);
	});
});
