import type { Column, DefaultValue, Extra, Index, LogicalType, Relation, Schema, SqlDialectId, Table } from '../model/types';
import { constraintName, quote } from './names';

export const INTEGER_KINDS = new Set(['smallint', 'int', 'bigint']);
export const TEMPORAL_KINDS = new Set(['date', 'time', 'timestamp', 'timestamptz']);
export const STRING_KINDS = new Set(['varchar', 'char', 'text']);
export const LOB_KINDS = new Set(['text', 'binary', 'json']);

export const DEFAULT_PRECISION: Record<SqlDialectId, [number, number]> = {
	postgres: [38, 10],
	mysql: [38, 10],
	sqlserver: [38, 10]
};

export function sqlType(dialect: SqlDialectId, type: LogicalType): string {
	switch (type.kind) {
		case 'raw':
			if (type.dialect === dialect) return type.sql;
			return dialect === 'sqlserver' ? 'NVARCHAR(MAX)' : 'TEXT';
		case 'varchar':
			if (dialect === 'postgres') return type.length ? `VARCHAR(${type.length})` : 'VARCHAR';
			if (dialect === 'mysql') return `VARCHAR(${type.length ?? 255})`;
			return (type.length ?? 255) > 4000 ? 'NVARCHAR(MAX)' : `NVARCHAR(${type.length ?? 255})`;
		case 'char':
			if (dialect === 'sqlserver') return `NCHAR(${type.length ?? 1})`;
			return type.length ? `CHAR(${type.length})` : 'CHAR(1)';
		case 'decimal': {
			const name = dialect === 'postgres' ? 'NUMERIC' : 'DECIMAL';
			if (type.precision === undefined) {
				if (dialect === 'postgres') return name;
				const [p, s] = DEFAULT_PRECISION[dialect];
				return `${name}(${p}, ${s})`;
			}
			return type.scale === undefined || type.scale === 0 ? `${name}(${type.precision})` : `${name}(${type.precision}, ${type.scale})`;
		}
		default:
			return SIMPLE[dialect][type.kind];
	}
}

const SIMPLE: Record<SqlDialectId, Record<string, string>> = {
	postgres: {
		uuid: 'UUID',
		smallint: 'SMALLINT',
		int: 'INTEGER',
		bigint: 'BIGINT',
		real: 'REAL',
		double: 'DOUBLE PRECISION',
		boolean: 'BOOLEAN',
		text: 'TEXT',
		date: 'DATE',
		time: 'TIME',
		timestamp: 'TIMESTAMP',
		timestamptz: 'TIMESTAMPTZ',
		json: 'JSONB',
		binary: 'BYTEA'
	},
	mysql: {
		uuid: 'CHAR(36)',
		smallint: 'SMALLINT',
		int: 'INT',
		bigint: 'BIGINT',
		real: 'FLOAT',
		double: 'DOUBLE',
		boolean: 'BOOLEAN',
		text: 'TEXT',
		date: 'DATE',
		time: 'TIME',
		timestamp: 'DATETIME(6)',
		timestamptz: 'TIMESTAMP(6)',
		json: 'JSON',
		binary: 'BLOB'
	},
	sqlserver: {
		uuid: 'UNIQUEIDENTIFIER',
		smallint: 'SMALLINT',
		int: 'INT',
		bigint: 'BIGINT',
		real: 'REAL',
		double: 'FLOAT',
		boolean: 'BIT',
		text: 'NVARCHAR(MAX)',
		date: 'DATE',
		time: 'TIME',
		timestamp: 'DATETIME2',
		timestamptz: 'DATETIMEOFFSET',
		json: 'NVARCHAR(MAX)',
		binary: 'VARBINARY(MAX)'
	}
};

export function stringLiteral(dialect: SqlDialectId, value: string): string {
	if (dialect === 'mysql') return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "''")}'`;
	if (dialect === 'sqlserver') return `N'${value.replaceAll("'", "''")}'`;
	return `'${value.replaceAll("'", "''")}'`;
}

function nowSql(dialect: SqlDialectId, kind: string): string | null {
	if (!TEMPORAL_KINDS.has(kind)) return null;
	if (dialect === 'postgres') return kind === 'date' ? 'CURRENT_DATE' : kind === 'time' ? 'LOCALTIME' : 'now()';
	if (dialect === 'mysql') return kind === 'date' ? '(CURRENT_DATE)' : kind === 'time' ? '(CURRENT_TIME)' : 'CURRENT_TIMESTAMP(6)';
	if (kind === 'timestamptz') return 'SYSDATETIMEOFFSET()';
	if (kind === 'date') return 'CAST(SYSDATETIME() AS DATE)';
	if (kind === 'time') return 'CAST(SYSDATETIME() AS TIME)';
	return 'SYSDATETIME()';
}

export function defaultSql(dialect: SqlDialectId, column: Column): string | null {
	const value: DefaultValue = column.default;
	const kind = column.type.kind;
	switch (value.kind) {
		case 'none':
		case 'autoincrement':
		case 'computed':
			return null;
		case 'now':
			return nowSql(dialect, kind);
		case 'uuid':
			if (kind !== 'uuid') return null;
			return dialect === 'postgres' ? 'gen_random_uuid()' : dialect === 'mysql' ? '(UUID())' : 'NEWID()';
		case 'expression':
			return value.dialect === dialect ? value.sql : null;
		case 'literal': {
			const v = value.value;
			let sql: string;
			if (v === null) sql = 'NULL';
			else if (typeof v === 'boolean') sql = dialect === 'sqlserver' ? (v ? '1' : '0') : v ? 'TRUE' : 'FALSE';
			else if (typeof v === 'number') sql = String(v);
			else sql = stringLiteral(dialect, v);
			const rawLob = column.type.kind === 'raw' && /blob|text|json/i.test(column.type.sql);
			return dialect === 'mysql' && v !== null && (LOB_KINDS.has(kind) || rawLob) ? `(${sql})` : sql;
		}
	}
}

export function identitySql(dialect: SqlDialectId, column: Column): string | null {
	if (column.default.kind !== 'autoincrement' || !INTEGER_KINDS.has(column.type.kind)) return null;
	if (dialect === 'postgres') return 'GENERATED BY DEFAULT AS IDENTITY';
	if (dialect === 'mysql') return 'AUTO_INCREMENT';
	return 'IDENTITY(1,1)';
}

export function columnById(table: Table, id: string): Column | undefined {
	return table.columns.find((c) => c.id === id);
}

function keyColumn(dialect: SqlDialectId, table: Table, id: string): string {
	const column = columnById(table, id);
	if (!column) return '';
	const name = quote(dialect, column.name);
	if (dialect === 'mysql' && (column.type.kind === 'text' || column.type.kind === 'binary')) return `${name}(255)`;
	return name;
}

export function keyList(dialect: SqlDialectId, table: Table, ids: string[]): string {
	return ids.map((id) => keyColumn(dialect, table, id)).filter(Boolean).join(', ');
}

function inlineSafe(dialect: SqlDialectId, table: Table, id: string): boolean {
	const column = columnById(table, id);
	return !(dialect === 'mysql' && column && (column.type.kind === 'text' || column.type.kind === 'binary'));
}

export function columnLine(dialect: SqlDialectId, table: Table, column: Column, inlinePk: boolean, inlineUnique: boolean): string {
	const computed = column.default.kind === 'computed' && column.default.dialect === dialect ? column.default.sql : null;
	if (computed !== null && dialect === 'sqlserver') return `${quote(dialect, column.name)} ${computed}`;
	const parts = [quote(dialect, column.name), sqlType(dialect, column.type)];
	if (computed !== null) {
		parts.push(computed);
		return parts.join(' ');
	}
	const identity = identitySql(dialect, column);
	if (identity) parts.push(identity);
	const isPk = table.primaryKey.includes(column.id);
	if ((!column.nullable || isPk) && !inlinePk && !identity) parts.push('NOT NULL');
	const def = defaultSql(dialect, column);
	if (def !== null) parts.push(`DEFAULT ${def}`);
	if (inlinePk) parts.push('PRIMARY KEY');
	if (inlineUnique) parts.push('UNIQUE');
	if (dialect === 'sqlserver' && column.type.kind === 'json') parts.push(`CHECK (ISJSON(${quote(dialect, column.name)}) = 1)`);
	if (dialect === 'mysql' && column.comment) parts.push(`COMMENT ${stringLiteral(dialect, column.comment)}`);
	return parts.join(' ');
}

export function createTable(dialect: SqlDialectId, table: Table): string {
	const lines: string[] = [];
	const singlePk = table.primaryKey.length === 1 && !table.primaryKeyName ? table.primaryKey[0] : undefined;
	const pkInline = singlePk !== undefined && inlineSafe(dialect, table, singlePk);
	const inlineUniques = new Set(
		table.uniques
			.filter((u) => u.columns.length === 1 && !u.name && u.columns[0] !== singlePk && inlineSafe(dialect, table, u.columns[0] ?? ''))
			.map((u) => u.columns[0] ?? '')
	);
	for (const column of table.columns) {
		lines.push(columnLine(dialect, table, column, pkInline && column.id === singlePk, inlineUniques.has(column.id)));
	}
	if (table.primaryKey.length > 0 && !pkInline) {
		const prefix = table.primaryKeyName ? `CONSTRAINT ${quote(dialect, table.primaryKeyName)} ` : '';
		lines.push(`${prefix}PRIMARY KEY (${keyList(dialect, table, table.primaryKey)})`);
	}
	for (const unique of table.uniques) {
		if (unique.columns.length === 1 && inlineUniques.has(unique.columns[0] ?? '') && !unique.name) continue;
		if (unique.columns.length === 0) continue;
		const prefix = unique.name ? `CONSTRAINT ${quote(dialect, unique.name)} ` : '';
		lines.push(`${prefix}UNIQUE (${keyList(dialect, table, unique.columns)})`);
	}
	let suffix = '';
	if (dialect === 'mysql') {
		suffix = ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4';
		if (table.comment) suffix += ` COMMENT=${stringLiteral(dialect, table.comment)}`;
	}
	const body = lines.length > 0 ? `\n  ${lines.join(',\n  ')}\n` : '';
	return `CREATE TABLE ${quote(dialect, table.name)} (${body})${suffix};`;
}

export function indexName(dialect: SqlDialectId, table: Table, ids: string[], unique: boolean): string {
	const names = ids.map((id) => columnById(table, id)?.name ?? id).join('_');
	return constraintName(dialect, `${unique ? 'ux' : 'ix'}_${table.name}_${names}`);
}

export function indexLabel(dialect: SqlDialectId, table: Table, index: Index): string {
	return index.name ?? indexName(dialect, table, index.columns, index.unique);
}

export function createIndex(dialect: SqlDialectId, table: Table, index: Index): string {
	return `CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${quote(dialect, indexLabel(dialect, table, index))} ON ${quote(dialect, table.name)} (${keyList(dialect, table, index.columns)});`;
}

export function createIndexes(dialect: SqlDialectId, table: Table): string[] {
	return table.indexes.filter((i) => i.columns.length > 0).map((index) => createIndex(dialect, table, index));
}

export function relationName(dialect: SqlDialectId | 'mongodb', relation: Relation, from: Table): string {
	if (relation.name) return relation.name;
	const names = relation.fromColumns.map((id) => columnById(from, id)?.name ?? id).join('_');
	return constraintName(dialect, `fk_${from.name}_${names}`);
}

function actionSql(dialect: SqlDialectId, kind: 'DELETE' | 'UPDATE', action: Relation['onDelete']): string {
	if (action === 'NO ACTION') return '';
	if (action === 'RESTRICT' && dialect === 'sqlserver') return '';
	return ` ON ${kind} ${action}`;
}

export function foreignKey(dialect: SqlDialectId, schema: Schema, relation: Relation): string | null {
	const from = schema.tables.find((t) => t.id === relation.fromTable);
	const to = schema.tables.find((t) => t.id === relation.toTable);
	if (!from || !to) return null;
	const fromCols = relation.fromColumns.map((id) => columnById(from, id));
	const toCols = relation.toColumns.map((id) => columnById(to, id));
	if (fromCols.some((c) => !c) || toCols.some((c) => !c)) return null;
	const list = (cols: (Column | undefined)[]) => cols.map((c) => quote(dialect, c?.name ?? '')).join(', ');
	return [
		`ALTER TABLE ${quote(dialect, from.name)}`,
		`  ADD CONSTRAINT ${quote(dialect, relationName(dialect, relation, from))}`,
		`  FOREIGN KEY (${list(fromCols)}) REFERENCES ${quote(dialect, to.name)} (${list(toCols)})${actionSql(dialect, 'DELETE', relation.onDelete)}${actionSql(dialect, 'UPDATE', relation.onUpdate)};`
	].join('\n');
}

export function comments(dialect: SqlDialectId, table: Table): string[] {
	const out: string[] = [];
	if (dialect === 'postgres') {
		if (table.comment) out.push(`COMMENT ON TABLE ${quote(dialect, table.name)} IS ${stringLiteral(dialect, table.comment)};`);
		for (const c of table.columns) {
			if (c.comment) out.push(`COMMENT ON COLUMN ${quote(dialect, table.name)}.${quote(dialect, c.name)} IS ${stringLiteral(dialect, c.comment)};`);
		}
	}
	if (dialect === 'sqlserver') {
		const property = (value: string, column?: string) =>
			`EXEC sys.sp_addextendedproperty @name = N'MS_Description', @value = ${stringLiteral(dialect, value)}, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = ${stringLiteral(dialect, table.name)}${column === undefined ? '' : `, @level2type = N'COLUMN', @level2name = ${stringLiteral(dialect, column)}`};`;
		if (table.comment) out.push(property(table.comment));
		for (const c of table.columns) if (c.comment) out.push(property(c.comment, c.name));
	}
	return out;
}

const BATCH_ALONE = /^\s*CREATE\s+(OR\s+ALTER\s+)?(VIEW|PROC|PROCEDURE|FUNCTION|TRIGGER|SCHEMA)\b/i;

function extraSql(dialect: SqlDialectId, extra: Extra): string {
	const text = extra.sql.trim().replace(/;\s*$/, '');
	if (dialect === 'sqlserver' && BATCH_ALONE.test(text)) return `GO\n${text};\nGO`;
	return `${text};`;
}

function noteLines(schema: Schema): string[] {
	return schema.notes
		.filter((n) => n.text.trim())
		.map((n) =>
			n.text
				.trim()
				.split(/\r?\n/)
				.map((line) => `-- ${line}`.trimEnd())
				.join('\n')
		);
}

export function generateSql(dialect: SqlDialectId, schema: Schema): string {
	const blocks: string[] = [];
	blocks.push(...noteLines(schema));
	const extras = schema.extras.filter((e) => e.dialect === dialect);
	blocks.push(...extras.filter((e) => e.placement === 'before').map((e) => extraSql(dialect, e)));
	blocks.push(...schema.tables.map((t) => createTable(dialect, t)));
	blocks.push(...schema.tables.flatMap((t) => createIndexes(dialect, t)));
	blocks.push(...schema.relations.map((r) => foreignKey(dialect, schema, r)).filter((s): s is string => s !== null));
	blocks.push(...schema.tables.flatMap((t) => comments(dialect, t)));
	blocks.push(...extras.filter((e) => e.placement === 'after').map((e) => extraSql(dialect, e)));
	return blocks.length > 0 ? `${blocks.join('\n\n')}\n` : '';
}
