import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';
import { parseSql } from '../parse/sql-parse';
import { loadTemplates } from '../templates/template';
import type { SqlDialectId } from '../model/types';
import { dbml } from './dbml';
import { drizzle } from './drizzle';
import { prisma } from './prisma';
import { typescript } from './typescript';
import { zod } from './zod';

const SQL = `
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  nickname VARCHAR(30),
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  profile JSONB,
  avatar BYTEA,
  token UUID DEFAULT gen_random_uuid(),
  manager_id BIGINT
);
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT,
  body TEXT NOT NULL,
  sent_at TIMESTAMP DEFAULT now()
);
CREATE TABLE order_lines (
  order_id INTEGER NOT NULL,
  line_no SMALLINT NOT NULL,
  qty INTEGER NOT NULL DEFAULT 1,
  note VARCHAR(80),
  PRIMARY KEY (order_id, line_no)
);
CREATE TABLE profiles (user_id BIGINT PRIMARY KEY, bio TEXT);
ALTER TABLE messages ADD CONSTRAINT fk_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT fk_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT fk_manager FOREIGN KEY (manager_id) REFERENCES users (id);
ALTER TABLE profiles ADD CONSTRAINT fk_profile FOREIGN KEY (user_id) REFERENCES users (id);
CREATE INDEX ix_messages_sender ON messages (sender_id, sent_at);
CREATE TABLE "Weird Name" ("select" INTEGER PRIMARY KEY, "2nd col" VARCHAR(50), UNIQUE ("select", "2nd col"));
`;

const problems = (code: string) => (ts.transpileModule(code, { reportDiagnostics: true, compilerOptions: { target: ts.ScriptTarget.ES2022 } }).diagnostics ?? []).map((d) => ts.flattenDiagnosticMessageText(d.messageText, ' '));

const parsed = parseSql('postgres', SQL);
const schema = { ...parsed.schema, name: 'fixture' };

describe('fixture', () => {
	it('parses without errors', () => {
		expect(parsed.issues.filter((i) => i.blocking)).toEqual([]);
		expect(schema.tables).toHaveLength(5);
		expect(schema.relations).toHaveLength(4);
	});
});

describe('prisma', () => {
	const text = prisma(schema, 'postgres');

	it('names the two relations between the same models', () => {
		expect(text).toContain('@relation("MessagesSender", fields: [senderId], references: [id], onDelete: Cascade, onUpdate: NoAction)');
		expect(text).toContain('@relation("MessagesReceiver", fields: [receiverId], references: [id], onDelete: SetNull, onUpdate: NoAction)');
		expect(text).toMatch(/messagesSender\s+Messages\[\]\s+@relation\("MessagesSender"\)/);
		expect(text).toMatch(/messagesReceiver\s+Messages\[\]\s+@relation\("MessagesReceiver"\)/);
	});

	it('adds back-relations, one-to-one and self-relations', () => {
		expect(text).toMatch(/profiles\s+Profiles\?/);
		expect(text).toMatch(/manager\s+Users\?\s+@relation\("UsersManager"/);
		expect(text).toMatch(/@relation\("UsersManager"\)/);
	});

	it('handles composite keys, maps and native types', () => {
		expect(text).toContain('@@id([orderId, lineNo])');
		expect(text).toContain('@@map("order_lines")');
		expect(text).toContain('@@index([senderId, sentAt])');
		expect(text).toContain('@db.VarChar(100)');
		expect(text).toContain('@db.Decimal(12, 2)');
		expect(text).toContain('@default(autoincrement())');
		expect(text).toContain('@default(now())');
		expect(text).toMatch(/nickname\s+String\?/);
		expect(text).toContain('provider = "postgresql"');
	});

	it('changes the provider and the native types per engine', () => {
		const sqlserver = prisma(schema, 'sqlserver');
		expect(sqlserver).toContain('provider = "sqlserver"');
		expect(sqlserver).toContain('@db.NVarChar(100)');
		expect(prisma(schema, 'mysql')).toContain('@db.Text');
	});
});

describe('prisma keys on text columns', () => {
	const textKeys = parseSql('postgres', 'CREATE TABLE s (id TEXT PRIMARY KEY, slug TEXT UNIQUE, a TEXT NOT NULL, b TEXT NOT NULL, UNIQUE (a, b)); CREATE INDEX ix_s_ab ON s (a, b);').schema;

	it('gives MySQL a prefix length, as the SQL does, because it cannot index a whole text column', () => {
		const text = prisma(textKeys, 'mysql');
		expect(text).toContain('@id(length: 255)');
		expect(text).toContain('@unique(length: 255)');
		expect(text).toContain('@@unique([a(length: 255), b(length: 255)])');
		expect(text).toContain('@@index([a(length: 255), b(length: 255)])');
	});

	it('leaves the other engines without a prefix', () => {
		expect(prisma(textKeys, 'postgres')).not.toContain('length:');
		expect(prisma(textKeys, 'sqlserver')).not.toContain('length:');
	});
});

describe('drizzle', () => {
	const pg = drizzle(schema, 'postgres');

	it('uses the postgres builders and references', () => {
		expect(pg).toContain("from 'drizzle-orm/pg-core'");
		expect(pg).toContain("id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity()");
		expect(pg).toContain("createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()");
		expect(pg).toContain("senderId: bigint('sender_id', { mode: 'number' }).notNull().references(() => users.id, { onDelete: 'cascade' })");
		expect(pg).toContain('primaryKey({ columns: [t.orderId, t.lineNo] })');
		expect(pg).toContain('foreignKey({ columns: [t.managerId], foreignColumns: [t.id] })');
		expect(pg).toContain("index('ix_messages_sender').on(t.senderId, t.sentAt)");
	});

	it('uses the mysql builders and does not support SQL Server', () => {
		const my = drizzle(schema, 'mysql');
		expect(my).toContain("from 'drizzle-orm/mysql-core'");
		expect(my).toContain('.autoincrement()');
		expect(drizzle(schema, 'sqlserver')).toBe('');
	});
});

describe('dbml', () => {
	const text = dbml(schema, 'postgres');

	it('writes tables, keys, references and indexes', () => {
		expect(text).toContain("database_type: 'PostgreSQL'");
		expect(text).toContain('Table users {');
		expect(text).toMatch(/id\s+BIGINT\s+\[pk, increment\]/);
		expect(text).toContain('(order_id, line_no) [pk]');
		expect(text).toContain('Ref fk_sender: messages.sender_id > users.id [delete: cascade]');
		expect(text).toContain('Ref fk_profile: profiles.user_id - users.id');
		expect(text).toContain('Table "Weird Name" {');
	});
});

describe('typescript and zod', () => {
	it('makes columns with defaults optional on insert', () => {
		const text = typescript(schema, 'postgres');
		expect(text).toContain('export interface Users {');
		expect(text).toMatch(/export interface UsersInsert \{[^}]*\bid\?: number;/);
		expect(text).toMatch(/email: string;/);
		expect(text).toMatch(/nickname\?: string \| null;/);
		expect(text).toContain('balance: string;');
	});

	it('writes zod schemas with limits', () => {
		const text = zod(schema, 'postgres');
		expect(text.startsWith("import { z } from 'zod';")).toBe(true);
		expect(text).toContain('email: z.string().max(100),');
		expect(text).toContain('nickname: z.string().max(30).nullable(),');
		expect(text).toContain('z.string().regex(/^-?\\d+(\\.\\d+)?$/)');
		expect(text).toContain('export const usersInsertSchema = usersSchema.partial({');
	});
});

describe('hostile names', () => {
	const hostile = "a'b\"c\\d\n*/ ${x} `e` ]] </script> \u2028 end";
	const hostileSchema = JSON.parse(JSON.stringify(schema)) as typeof schema;
	hostileSchema.tables.forEach((table, i) => {
		table.name = `${hostile}${i}`;
		table.comment = hostile;
		table.columns.forEach((column, j) => {
			column.name = `${hostile}${j}`;
			column.comment = hostile;
		});
	});

	it('keeps every TypeScript output valid', () => {
		expect(problems(typescript(hostileSchema, 'postgres'))).toEqual([]);
		expect(problems(zod(hostileSchema, 'postgres'))).toEqual([]);
		expect(problems(drizzle(hostileSchema, 'postgres'))).toEqual([]);
		expect(problems(drizzle(hostileSchema, 'mysql'))).toEqual([]);
	});

	it('does not let a name close a comment or a string in the other outputs', () => {
		const text = prisma(hostileSchema, 'postgres');
		expect(text.split('\n').filter((line) => /^\s*DROP|^\s*<\/script/i.test(line))).toEqual([]);
		const note = dbml(hostileSchema, 'postgres');
		expect(note.split(/\r\n|\r|\n|\u2028|\u2029/).filter((line) => !/^(\}|Project |Table |Ref |  |$)/.test(line))).toEqual([]);
	});
});

describe('every template of the library', async () => {
	const templates = await loadTemplates();

	it('has templates to try', () => {
		expect(templates.length).toBeGreaterThan(0);
	});

	for (const template of templates) {
		it(template.id, () => {
			const schema = parseSql('postgres', template.sql).schema;
			for (const dialect of ['postgres', 'mysql', 'sqlserver'] as const) {
				expect(problems(typescript(schema, dialect)), `typescript ${dialect}`).toEqual([]);
				expect(problems(zod(schema, dialect)), `zod ${dialect}`).toEqual([]);
				expect(prisma(schema, dialect)).toContain('model ');
				expect(dbml(schema, dialect)).toContain('Table ');
				if (dialect !== 'sqlserver') expect(problems(drizzle(schema, dialect)), `drizzle ${dialect}`).toEqual([]);
			}
		});
	}
});

describe('dump', () => {
	it.runIf(Boolean(process.env.SF_DUMP))('writes every output for external validation', async () => {
		const dir = process.env.SF_DUMP as string;
		mkdirSync(dir, { recursive: true });
		for (const dialect of ['postgres', 'mysql', 'sqlserver'] as SqlDialectId[]) {
			writeFileSync(join(dir, `schema.${dialect}.prisma`), prisma(schema, dialect));
		}
		writeFileSync(join(dir, 'drizzle.pg.ts'), drizzle(schema, 'postgres'));
		writeFileSync(join(dir, 'drizzle.mysql.ts'), drizzle(schema, 'mysql'));
		writeFileSync(join(dir, 'fixture.dbml'), dbml(schema, 'postgres'));
		writeFileSync(join(dir, 'types.ts'), typescript(schema, 'postgres'));
		writeFileSync(join(dir, 'schemas.ts'), zod(schema, 'postgres'));
		writeFileSync(join(dir, 'prefix.mysql.prisma'), prisma(parseSql('postgres', 'CREATE TABLE s (id TEXT PRIMARY KEY, slug TEXT UNIQUE, a TEXT NOT NULL, b TEXT NOT NULL, UNIQUE (a, b)); CREATE INDEX ix_s_ab ON s (a, b);').schema, 'mysql'));
		mkdirSync(join(dir, 'templates'), { recursive: true });
		for (const template of await loadTemplates()) {
			const each = parseSql('postgres', template.sql).schema;
			for (const dialect of ['postgres', 'mysql', 'sqlserver'] as SqlDialectId[]) writeFileSync(join(dir, 'templates', `${template.id}.${dialect}.prisma`), prisma(each, dialect));
			writeFileSync(join(dir, 'templates', `${template.id}.dbml`), dbml(each, 'postgres'));
			writeFileSync(join(dir, 'templates', `${template.id}.types.ts`), typescript(each, 'postgres'));
			writeFileSync(join(dir, 'templates', `${template.id}.zod.ts`), zod(each, 'postgres'));
			writeFileSync(join(dir, 'templates', `${template.id}.drizzle.ts`), drizzle(each, 'postgres'));
		}
	});
});
